import './js/about-me.js';
import './js/benefits.js';
import './js/covers.js';
import './js/faq.js';
import './js/header.js';
import './js/hero.js';
import './js/projects.js';
import './js/reviews.js';
import './js/work-together.js';